Add logic path to disable Managed Identity
juju-solutions/interface-azure-integration pull request #6
Opened 2021-05-10 08:07 UTC by VariableDeclared

Managed Identity requires a "Owner" service principal
to create and manage role assignments for the managed
identities (VMs). This presents the problem of creating
a service principal with such permissions (Application credential).

Creating such application credentials present a grave security
risk which is mitigated with this change. This change
allows Charmed Kubernetes to use the service principal directly,
as opposed to a service principal which assigns roles to VMs
the VMs utilise a SP that already has the roles required.

Related [PR](https://github.com/juju-solutions/charm-azure-integrator/pull/30)

 

- [ ] Test disable managed identity path
- [ ]  Test "credentials" file path
- [ ]  Test juju grant path

2021-05-18 16:20 UTC, johnsca reviewed
I'm quite unclear as to why the client ID, secret, and tenant ID need to be broken out and sent separately in addition to the credentials.  And as I mentioned in the other PR, I'm confused as to whether `managed-identity` is also expected to be part of the credentials and maybe this change isn't needed at all.

2021-05-27 14:21 UTC, johnsca requested changes
Would you mind please either dropping or populating with these values the (currently unused) `credentials` property on the requires side, so as to avoid confusion?

2021-05-27 14:31 UTC, VariableDeclared commented
Thank you @johnsca, removed!

2021-05-28 17:50 UTC, johnsca approved these changes

2021-05-28 17:51 UTC, merged